### ISSUE TITLE
`NotoSansLao-Regular.ttf`: bad design of glyph uni0ED8?

### ISSUE THREAD

**Issue by lemzwerg** [notofonts/lao#1]
[commit abed4e560220062e1a0a1dd5623cf1922acbc639]

Here are two (unhinted) images of glyphs `uni0ED8` and `uni0ED9` from font `NotoSansLao-Regular.ttf`.

![notosanslao-regular uni0ed8](https://cloud.githubusercontent.com/assets/1630245/10121276/70f2e2e8-64e4-11e5-8f6d-1f43a94eb498.png)

![notosanslao-regular uni0ed9](https://cloud.githubusercontent.com/assets/1630245/10121278/7d26ed5c-64e4-11e5-9d70-93aef3ee0385.png)

What's the reason that the 'baseline loop' in `uni0ED8` is lower than in `uni0ED9`?  This inconsistency causes bad rendering with the forthcoming auto-hinting support of the Lao script in FreeType...

In general, the loop positions and its diameters are very inconsistent in this font.  I suggest to harmonize them.

**Comment by ohbendy** [comment]
(The original image is from a very old version of Noto Sans Lao. I'd suggest this issue can be closed)
