### ISSUE TITLE
Completely rename "Noto Looped Thai" and "Noto Looped Lao" to "Noto Sans Thai Looped" and "Noto Sans Lao Looped" 

### ISSUE THREAD

**Issue by twardoch** [notofonts/lao#3]
We have "Noto Looped Thai" and "Noto Looped Lao" (and the UI variants), but the GF API onboarded the first one as "Noto Sans Thai Looped". 

I applaud that change and we should do it upstream & in sources.

**Comment by simoncozens** [comment]
Done this for Thai, currently doing it for Lao.

**Comment by simoncozens** [comment]
(Done in c29845a, in fact)
